### ISSUE TITLE
[Bug]:  Got Request Entity Too Large when uploading file more than 128mb

### ISSUE THREAD

**Issue by handhikadj** [beyondcode/herd-community#248]
### Operating system version

MacOS Ventura 13.0

### System architecture

ARM64 (M1, M2, etc)

### Herd Version

1.3.1

### PHP Version

PHP 8.1

### Bug description

Got Request Entity Too Large when uploading a file more than 128mb

already increase sizes on config files (nginx, php.ini, and herd setting) and run `herd restart`, still doesn't work

<img width="772" alt="image" src="https://github.com/beyondcode/herd-community/assets/22522638/c1adf62f-b1af-487f-afc5-eb01899945b0">

I also can see on `phpinfo()` , the post_max_size and upload_max_filesize is still 128M . it's still like not reflected

php.ini:
```
curl.cainfo=/Users/me/Library/Application Support/Herd/config/php/cacert.pem
openssl.cafile=/Users/me/Library/Application Support/Herd/config/php/cacert.pem
pcre.jit=0
post_max_size = 1000M
memory_limit=1000M
upload_max_filesize=1000M
```

### Steps to reproduce

1. create `<input type "file" />` on html
2. upload file more than 128mb
(I'm actually getting this on Laravel Nova on File field)

**Comment by Ihabafia** [comment]
I noticed that if you use php 8.1 it will increase the Max File upload, while if you use php 8.0 or 8.2 it will stay as 128MB.

**Comment by benmAltDesign** [comment]
Happening here too. I thought this would be some kind of legacy issue from Valet so I did a --force uninstall on Valet, restarted my mac but nothing here. I've confirmed in phpinfo() that the php.ini being used is the herd one and I've set the file upload to 1gb which should be easily enough for the files I'm working with.

**Comment by benmAltDesign** [comment]
@handhikadj Has this been fixed in a new version?

**Comment by tyroga** [comment]
Wait OP closed this one without a fix? I am having this issue too.

Fresh Herd Install to try and resolve but still no fix.

> <b>Warning</b>:  POST Content-Length of 190108252 bytes exceeds the limit of 134217728 bytes in <b>Unknown</b> on line <b>0</b><br />

My php.ini (the one Herd uses)

```
curl.cainfo=/Users/[username]/Library/Application Support/Herd/config/php/cacert.pem
openssl.cafile=/Users/[username]/Library/Application Support/Herd/config/php/cacert.pem
pcre.jit=0
output_buffering=4096

memory_limit=512M
upload_max_filesize=500M
post_max_size=500M
```

But still reads as 128M in phpinfo and can't upload files above 128MB. 😵‍💫

MacOS 14.2.1 (23C71)
PHP 8.2.15
Herd 1.3.(build 19)

Herd settings :
Max file upload size: 500
Memory Limit: 512

Anyone got a fix?

**Comment by mpociot** [comment]
Can you check your FPM configuration?
The value could be overwritten there

**Comment by tyroga** [comment]
Thanks Marcel

This is what I have:

<img width="699" alt="Screenshot 2024-01-26 at 4 05 15 pm" src="https://github.com/beyondcode/herd-community/assets/6812136/a7b2a29d-a4fe-468b-9a6a-006cd347e0a8">

<img width="774" alt="Screenshot 2024-01-26 at 4 07 26 pm" src="https://github.com/beyondcode/herd-community/assets/6812136/4e4cd81d-351f-4116-9fc8-19fb1448f03a">

Am I looking in the right place? I recently uninstalled and reinstalled Herd trying to fix another issue with a site, was able to upload large files before that... now it doesn't seem to want to let me set these values via php.ini

**Comment by mpociot** [comment]
Please check the config file in ~/Library/Application Support/Herd/config/fpm

**Comment by tyroga** [comment]
OMGoodness I didn't know that it used a different config file other than the ini. 🤦‍♂️

Maybe https://herd.laravel.com/docs/1/advanced-usage/php-settings could be updated to reflect this?

Thanks so much for letting me know.

**Comment by handhikadj** [comment]
sorry that I closed this without a comment.
at that time, I'm getting nginx error that says something along this line: "the phpfpm.sock already running".
I fixed it and this fixed this issue

**Comment by alancwoo** [comment]
> Please check the config file in ~/Library/Application Support/Herd/config/fpm

I was really struggling to configure this as well and this finally solved it - but I don't understand why it was necessary still. The `8.2-fpm.conf` specifically mentions `When uncommented, the following values will take precedence over settings declared elsewhere` and were uncommented, so nothing was being modified there.

So why is the loaded `php.ini` as configured by both the Herd GUI and also in the file itself not respected? In my case it was stuck at `2M` in all cases.

**Comment by mhomeister** [comment]
I have the same issue, i have all my settings set to 100M, my .conf files in `~/Library/Application Support/Herd/config/fpm` and in all php.ini files in `~/Library/Application Support/Herd/config/php/VERSION/php.ini`

The GUI says its at 100M but im not able to upload files more than 15Mb

**Comment by fpolli** [comment]
Anyone solve this? I have edited the php.ini based on the instructions in the Herd docs and the php-fpm conf file as in this thread, and Herd still won't change the limits. This is really frustrating.
