### ISSUE TITLE
[Bug]: The system cannot find the path specified

### ISSUE THREAD

**Issue by asciito** [beyondcode/herd-community#651]
### Platform

Windows

### Operating system version

Windows 11 Home Single Language

### System architecture

Intel (x86)

### Herd Version

1.0.1termina

### PHP Version

8.3

### Bug description

The next bug is simple to fix, I do it my self.

When I install Herd on my Windows machine, everytime I try to run the command `herd`, or `php`, etc, I always recieve the message: `The system cannot find the path specified`. I'm not even an expert on windows but I found that the problem is releated with the name of my current user (folder) containt an accent mark and a space.

Let say, e.g. `C:\User\José Perengano`, so the problem was in the `php.bat` file (and all the other `.bat` files that contain the full path), I just replace the base part with the variable `%USERPROFILE%` and the path looks like this `"%USERPROFILE%\.config\herd\bin\php83\php.exe" %*`.

I tried to solve the problem just scaping the space, but that doesn't work so I choose to use the system variable.

### Steps to reproduce

Create a local user on a Windows Machine, and the user folder should have to contain a space, and an accent mark

### Relevant log output

```shell
The system cannot find the path specified
```

**Comment by sschlein** [comment]
I have fixed that but we are going to test this to see if there are any side effects that we don't know about. So it'll be in a release soon! :)

**Comment by andersmandersen** [comment]
I have got the same problem, just with a danish character. Just letting you know if your are looking into that area :) 

My path is "C:\Users\AndersMøllerAndersen"

**Comment by domagoj-skender-appliment** [comment]
Same problem with Croatian character and space, "C:\Users\Domagoj Škender", can't access PHP, Herd, Composer or Laravel commands via Powershell

**Comment by domagoj-skender-appliment** [comment]
Changed the path with %USERPROFILE% variable in the bat files, now laravel, php and composer commands work via CLI, but herd commands don't.

**Comment by Typhion** [comment]
This issue is still not fixed. If you have any special characters in your username you will just become unable to use the herd command in any way. For the other commands there are work arounds luckily.

**Comment by Typhion** [comment]
Changing the php version does not change anything. It is not PHP that has trouble with reading special chars, it is Herd that is unable to do this. Hope they fix this soon.

**Comment by timmydhooghe** [comment]
@sschlein Are you still testing this, or has it died a silent death?

**Comment by YacoubAl-hardari** [comment]
@mpociot  @sschlein PS C:\Users\postman\Herd\check> composer install
'php' is not recognized

**Comment by sorenstaun** [comment]
Same issue with "Søren" (my name). Changed to local account "admin", and everything worked.
